### PR TITLE
log maxActiveVoiceCountReached with Level.INFO #212

### LINKED ISSUE #212: fix: Reaching maxActiveVoiceCount should not raise a severe log event
**Description**

I guess I missed this in the previous PR review. It seems that the new version raises a severe log every time the max active voices count is reached. This is not a good idea.

**Steps To Reproduce**

1. Play lots of sounds at once.

**Expected Behavior**

Sounds over "budget" are dropped. An info-level message is generated.

**Screenshots**

Image

**Additional Context**

I really don't think that reaching the maximum voices is a SEVERE-type error. At most, it's a warning, but it's probably just an INFO-level event. In busy games, it is simply going to happen from time to time unless the developer sets some absurd limit.

### PR DESCRIPTION
**Pull request by alnitak**
## Description

Fixes #212

`PlayerErrors.maxActiveVoiceCountReached` should log with `Level.INFO` instead of `Level.SEVERE`.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

### CODE REVIEW

File: lib/src/soloud.dart [hunk 1]
```diff
@@ -2578,7 +2579,8 @@ interface class SoLoud {
       return;
     }
 
-    if (!_log.isLoggable(Level.SEVERE)) {
+    if (!_log.isLoggable(Level.SEVERE) &&
+        playerError != PlayerErrors.maxActiveVoiceCountReached) {
       // Do not do extra work if the logger isn't listening.
       return;
     }
```
Comment (filiph) [inline lib/src/soloud.dart:2586]:
```suggestion
    // Do not do extra work if the logger isn't listening
    // to the appropriate level.
    final logLevel = playerError == PlayerErrors.maxActiveVoiceCountReached
        ? Level.INFO
        : Level.SEVERE;

    if (!_log.isLoggable(logLevel)) {
      return;
    }
```

I got lost in this logic so I'm suggesting this change. It goes with the suggestion below.

File: lib/src/soloud.dart [hunk 2]
```diff
@@ -2588,6 +2590,10 @@ interface class SoLoud {
       strBuf.write('$from: ');
     }
     strBuf.write(playerError.toString());
-    _log.severe(strBuf.toString());
+    if (playerError == PlayerErrors.maxActiveVoiceCountReached) {
+      _log.info(strBuf.toString());
+    } else {
+      _log.severe(strBuf.toString());
+    }
```
Comment (filiph) [inline lib/src/soloud.dart:2597]:
```suggestion
    _log.log(logLevel, strBuf.toString());
```

**Review by filiph — APPROVED** [review]
LGTM with an optional improvement.
